name: Real Home Pipeline Execution test by Jeyson Valdivia

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
    types: [ opened, reopened, synchronize ]
  schedule: 
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        source venv/bin/activate
        pytest --alluredir=allure-results || true

    - name: Publish Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_branch: gh-pages
        publish_dir: allure-report



